[package]
name = "vialen-core"
version = "0.1.0"
edition = "2024"
license = "GPL-3.0-or-later"
publish = false

[lib]
name = "vialen_core"
crate-type = ["cdylib", "rlib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }

[profile.release]
opt-level = "z"
lto = "fat"
codegen-units = 1
strip = "symbols"
